apiVersion: v1
kind: Pod
metadata:
  name: virat-testpod
spec:
  containers:
  - name: virat-testpod
    image: tensorflow/tensorflow:1.13.1-gpu-py3
    args: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: "8Gi"
        cpu: "2000m"
      requests:
        nvidia.com/gpu: 1
        memory: "8Gi"
        cpu: "2000m"


    volumeMounts:
    - mountPath: /virat-vr
      name: virat-vr
  restartPolicy: Never
  volumes:
    - name: virat-vr
      persistentVolumeClaim:
        claimName: virat-vr
